// scene.js — the scene description. This file is the actual product.
//
// Everything else (the viewer, the Blender importer, the glTF exporter) is a
// reader of this format. Authoring happens here, in plain JSON, so a scene can
// be generated by a script, edited by hand, diffed in git, or handed to a
// model to fill in. Nothing is locked inside an app.

export const SCENE_VERSION = 1;

/**
 * @typedef {Object} Station
 * A source image plus the camera that was solved for it. Multiple stations
 * share one world, which is how several drawings build up a single set.
 * @property {string} id
 * @property {string} name
 * @property {string} src          data URL or relative path to the image
 * @property {number} width
 * @property {number} height
 * @property {number} focal        pixels
 * @property {number[]} rotation   16 floats, camera-to-world, column major
 * @property {number[]} position   [x, y, z]
 */

/**
 * @typedef {Object} Node
 * One thing in the world. Deliberately a small vocabulary: the goal is a
 * blockout, not a model.
 * @property {string} id
 * @property {'box'|'cylinder'|'card'|'ground'} type
 * @property {string} [name]
 * @property {number[]} position   [x, y, z], base-centred (y is the floor of the shape)
 * @property {number[]} size       box: [w,h,d]; cylinder: [r,h,r]; card: [w,h,0]
 * @property {number} rotationY    radians
 * @property {Object} material
 * @property {'projected'|'texture'|'flat'} material.mode
 * @property {string} [material.station]  station id to project from, when mode is projected
 * @property {string} [material.src]      image url, when mode is texture
 * @property {string} [material.color]    hex, when mode is flat
 * @property {number} [material.opacity]
 * @property {boolean} [material.doubleSided]
 * @property {number} [billboard]  0 = world-fixed, 1 = fully camera-facing
 * @property {string} [field]      id of the scatter field that emitted this node
 * @property {boolean} [pinned]    true once a human has touched it; survives re-rolls
 */

/**
 * @typedef {Object} ScatterField
 * A procedural population rule. Fields emit nodes. Emitted nodes stay in the
 * scene as ordinary editable nodes, so you can re-roll the field and keep the
 * handful you moved by hand.
 */

let counter = 0;
export function uid(prefix = 'n') {
  counter += 1;
  return `${prefix}_${Date.now().toString(36)}_${counter.toString(36)}`;
}

export function emptyScene() {
  return {
    version: SCENE_VERSION,
    name: 'untitled set',
    /** metres per world unit; only matters when handing off to Blender */
    unitScale: 1,
    stations: [],
    nodes: [],
    fields: [],
    cameraPath: null,
  };
}

export function defaultField(overrides = {}) {
  return {
    id: uid('field'),
    name: 'scatter',
    enabled: true,
    seed: 1,
    count: 60,
    /** where instances land */
    domain: {
      type: 'ground', // 'ground' | 'box' | 'shell' | 'spline'
      center: [0, 0, -12],
      size: [24, 6, 24],
      /** keep instances out of this radius around the camera path */
      exclude: 0,
    },
    /** which cutouts get used, cycled or picked at random per instance */
    sources: [],
    scale: { min: 0.8, max: 2.4 },
    /** 0 = upright and world-fixed, 1 = always facing the camera */
    billboard: 1,
    rotationJitter: 0.15,
    /** push instances into discrete depth bands for a cleaner multiplane read */
    depthBands: 0,
    tint: { amount: 0, from: '#ffffff', to: '#ffffff' },
    opacity: { min: 1, max: 1 },
    /**
     * When set to a station id, each instance samples that station's image at
     * its own projected position and tints itself with what it finds. The
     * collage then grows out of the drawing instead of being sprinkled on it.
     */
    sampleColorFrom: null,
  };
}

export function serialize(scene) {
  return JSON.stringify(scene, null, 2);
}

export function deserialize(text) {
  const data = typeof text === 'string' ? JSON.parse(text) : text;
  if (data.version !== SCENE_VERSION) {
    console.warn(
      `scene version ${data.version} does not match ${SCENE_VERSION}; loading anyway`,
    );
  }
  return { ...emptyScene(), ...data };
}

/** Nodes a given field owns and is therefore allowed to replace on re-roll. */
export function fieldNodes(scene, fieldId) {
  return scene.nodes.filter((n) => n.field === fieldId);
}

/**
 * Replace a field's generated nodes while preserving any the user has pinned.
 * This is the one rule that makes the procedural side usable: a parameter
 * change must never throw away hand work.
 */
export function replaceFieldNodes(scene, fieldId, fresh) {
  const kept = scene.nodes.filter((n) => n.field !== fieldId || n.pinned);
  scene.nodes = kept.concat(fresh);
  return scene;
}
